[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
"actix-web"="*"
tokio = { version = "*", features = ["macros", "rt-multi-thread"] }
serde = { version = "*", features = ["derive"]}
reqwest="*"
sqlx = { version = "*", default-features = false, features = [ "runtime-actix-rustls", "macros", "postgres", "uuid", "chrono", "migrate", "offline"] }

uuid = { version = "*", features = ["v4", "serde"] }
chrono="*"
# log="*"
config="*"
# env_logger="*"
tracing = { version = "*", features = ["log"] }
tracing-subscriber = { version = "*", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "*"
tracing-log = "*"
once_cell="*"
secrecy = { version = "*", features = ["serde"] }
tracing-actix-web="*"